### ISSUE TITLE
Pooling/reuse of SAEA in SocketConnection

### ISSUE THREAD

**Issue by matthew798** [mgravell/Pipelines.Sockets.Unofficial#10]
I've had a great time reading/analyzing/learning from this library. I came across a bit of code that had me wondering if I've been using SocxketAsyncEventArgs wrong.

In SocketConnection.Receive.cs, you don't re-use (pool) the SAEA.

Specifically, this line is called on each loop of the `DoReadAsync()` function:

` _readerArgs = new SocketAwaitableEventArgs(InlineReads ? null : _receiveOptions.WriterScheduler);`

I'm curious to know if this is deliberate. Most of the information I've read about SAEA so far seems to suggest pooling them for re-use.

**Comment by mgravell** [comment]
I may be misremembering the code (not at a PC), but: that happens once per socket, with it then being reused for all reads for that socket. So: it isn't as though I'm creating them constantly.

Are you saying I should reuse them *between* sockets? That is indeed possible, but I'm not sure how much it would benefit things, if we assume that most sockets are reasonably long-lived.

**Comment by mgravell** [comment]
I've checked the code (always fun on mobile), and that definitely happens *outside* the loop, unless I'm missing something.

**Comment by matthew798** [comment]
Holy moly I really misread. You are right, it's outside the loop. I think I went too fast and saw the "try" as a "while".

**Comment by matthew798** [comment]
As a loosely related follow-up, is there any way to "swap" out the socket on a SocketConnection? In other words, is possible to avoid creating a new SocketConnection for each new client?

**Comment by mgravell** [comment]
Not currently. It probably can be, though - pretty sure I remember `Pipe` being resettable. So really it would come down to what we'd expect it to look like - i.e. how so we cleanly shut it down in a way that is usefully reusable. I haven't spent the time to figure that out. I'm open to ideas.

**Comment by matthew798** [comment]
I'm thinking:

1.  a constructor without a socket
2. exposing the socket as a public property (maybe better to have a SetSocket() method??) 
3. implementing a Reset() that just calls Reset() on both pipes.
4. Start() and Stop() methods that kick off and kill the Do**Async loops.

Then the consumer would do:

```
new SocketConnection.Create(socket, ...);
...
SocketConnection.Stop();
SocketConnection.SetSocket(newSocket);
SocketConnection.Reset();
SocketConnection.Start();
```

Could probably wrap the whole functionality into a SwapSocket(Socket socket) method or something.

Different combinations of the above methods could satisfy different scenarios.

I've had a great time going over your code. I'm using it to come up with my own implementation, mostly to learn. So far your library has been a great resource. Thanks!

**Comment by matthew798** [comment]
I totally agree that if it can't be implemented *very* elegantly, or trivially, it may not be worth it. It just seems to me that, even without any of the functionality I mentioned above (Stop(), Reset(), Start()...) there may still be a way to implement it reliably. I'll see what I can come up with. 

P.S. where is a good place to ask questions about this library specifically? I feel bad starting a new issue just to ask a question...

**Comment by mgravell** [comment]
Here is probably fine.
