### ISSUE TITLE
Protocol with length in front

### ISSUE THREAD

**Issue by aensidhe** [mgravell/Pipelines.Sockets.Unofficial#14]
[Protocol of database Tarantool](https://tarantool.io/en/doc/1.9/dev_guide/internals_index/#unified-packet-structure) requires you to write length of packet in front of it, it can be kinda tricky, you know, since protocol is msgpack and user can use strings, so I don't know that length until I do full serialization.

I do simple test now (`sc` is `SocketConnection`):

```csharp
var offset = 10;
var bytes = sc.Output.GetMemory(100);
var length = Write(bytes.Span.Slice(offset, bytes.Length - offset));

bytes = sc.Output.GetMemory(100); // <--- here we got same buffer as above
length += Write(bytes.Span);

length += AddCrLf(bytes.Span.Slice(bytes.Length - 2));

Encoding.ASCII.GetBytes(length.ToString(), bytes.Span.Slice(0, offset));

sc.Output.Advance(length + offset);
```

And I get this exception:

```
Unhandled Exception: System.InvalidOperationException: Can't advance past buffer size.
   at System.IO.Pipelines.ThrowHelper.ThrowInvalidOperationException_AdvancingPastBufferSize()
   at System.IO.Pipelines.Pipe.DefaultPipeWriter.Advance(Int32 bytes)
   at pipeline.client.Program.WorkWithSc(SocketConnection sc) in C:\Users\apopov\source\repos\github.com\aensidhe\pipeline.socket.unofficial.reproduction\pipeline.client\Program.cs:line 46
   at pipeline.client.Program.Main(String[] args) in C:\Users\apopov\source\repos\github.com\aensidhe\pipeline.socket.unofficial.reproduction\pipeline.client\Program.cs:line 23
```

How should I proceed in cases where my packet is not yet written because it's too large and I don't know length of it yet?

It seems that if I ask at second time for more memory that I did first time, pipe throws all the stuff away and I need to redo serialization from scratch. It's easier for writing, but it will be not as efficient as it could be.

```csharp
var bytes = sc.Output.GetMemory(100);
var length = Write(bytes.Span.Slice(offset, bytes.Length - offset));

bytes = sc.Output.GetMemory(bytes.Length + 1); // here we get empty buffer with zeroes in it
```

PS: protocol in illustration is ascii based with `\r\n` as packet separation for clarity and pipeline studying.

**Comment by mgravell** [comment]
Yeah, this is a pain. I don't have a specific answer to this, but it is
fundamentally the same problem you get on any transport including raw
sockets. FWIW I have the same problems in protobuf.

So: two options

1. change the library so you can calculate the length before serialization;
this can need significant design work
2. use a separate buffer, perhaps using the array-pool, to serialize - then
write the length and copy back

During the design sessions, we (we=some non-MS folks interested in the
tech) pushed for the inclusion of "external buffer" support, which would
allow 2 to be used directly without a second copy, but... we didn't win
that argument yet.

**Comment by aensidhe** [comment]
I explored options for calculation of length and they're not very promising:
1. User can place arbitrary string and use arbitrary encoding for that
2. User can choose to have an array of objects containing string
3. User can choose to have an array of objects with single root of inheritance and they can have different length.

I can try and implement some statistics gathering engine like sql server does, but I don't think that is a very feasible choice.

Also, msgpack has variable length integers and spec says that I should look specifically to value of int to serialize it to achieve smallest-possible representation. So, you know, calculating length is nearly impossible except I do full serialization pass (especially for strings).

Second option is how I do it now and I hoped to do it better. 

Thanks, anyway. 

Also, you can use my input in those design session, [34 stars](https://github.com/progaudi/progaudi.tarantool) is not a lot, but it's something.

**Comment by mgravell** [comment]
I'm familiar with the problems. Again: I'm a "protobuf" person, and
protobuf has variable length integers too. Same problems.

I'm currently quietly re-engineering V2 to support these ideas - it is
quite a large undertaking. But my question to you is: forget pipelines.
Pretend you're dealing with a file or raw socket. How would you solve this
same problem there? It is the same problem. It isn't really a pipelines
problem, but rather: an inherent problem is length-prefixed protocols.
Heck, even http has this problem (the content-length header).

Sometimes you just need to buffer.

**Comment by Drawaes** [comment]
I have suffered this pain and went through the pre calc method in the end. I also was advocating for external buffers that could be appended to the pipe. Even if such buffers had to come from the same pool that the pipe was using that would help

**Comment by mgravell** [comment]
I think the requested guidance covers this; closing - if something is still needed, let me know
