### ISSUE TITLE
Use a static DedicatedThreadPoolPipeScheduler by default

### ISSUE THREAD

**Issue by davidfowl** [mgravell/Pipelines.Sockets.Unofficial#15]
If multiple libraries use this library in an application, it'll end up spinning up a bunch of threads per use which would be less efficient that sharing them.

**Comment by mgravell** [comment]
So... you'd want something like `DedicatedThreadPoolPipeScheduler.Default` ?

**Comment by davidfowl** [comment]
Yea and that should be the default and libraries can opt into more isolation if they want to.
