### ISSUE TITLE
Is it possible to have a compiled version with .Net Framework 4.7.1?

### ISSUE THREAD

**Issue by AllTerrainDeveloper** [mgravell/Pipelines.Sockets.Unofficial#16]
I have a project which cannot be compiled against .Net Framework 4.7.2 as it is not fully supported yet for Roslyn compiler (Mono + Unix servers). Right now it only builds up to 4.7.1.

Any chance to have this library on Nuget supporting 4.7.1?

Cheers

**Comment by mgravell** [comment]
net471 will pick up the net461 build, which should work fine, no?

**Comment by AllTerrainDeveloper** [comment]
Yes, thank you. All solved
