### ISSUE TITLE
Complete SocketConnection pipe without disposing the underlying socket

### ISSUE THREAD

**Issue by xqrzd** [mgravell/Pipelines.Sockets.Unofficial#18]
I'm working on a client for Apache Kudu, using both your protobuf-net and this library, thanks!

The simplified exchange goes something like this (when first connecting to Kudu):

1) Send negotiate request PB
2) Do TLS handshake over PB
3) The remaining negotation happens over TLS
4) At the end of negotation, we may keep or drop TLS (depending on what the user decided)

What I attempted:

 - Create a Socket and SocketConnection
 - Do steps 1 and 2 above
 - Complete SocketConnection (I don't dispose the underlying socket)
 - Create a StreamConnection (SslStream -> InnerSslStream -> NetworkStream)
 - Do steps 3

Unfortunately completing the SocketConnection disposes the underlying socket. If I don't complete the SocketConnection, I end up with 2 pipes trying to read from the same socket.

Not sure if this is relevant, but since I have to do the TLS handshake over protobuf messages, this is a snippet of what I do in the InnerSslStream I pass to SslStream,

```csharp
public override Task WriteAsync(byte[] buffer, ...)
{
    if (_isAuthenticated)
    {
        _networkStream.WriteAsync(buffer, ...);
    }
    else
    {
        // Wrap TLS handshake in protobuf message
        _result = _negotiator.SendTlsHandshakeAsync(buffer);
    }
}
```

Do you have any advice for dealing with this scenario? The gist of it is I need to be able to switch to/from TLS at an arbitrary time.

**Comment by mgravell** [comment]
The way we do this in our code is to layer the SslStream on top of the
pipe, rather than on a NetworkStream. There are adapters in the library for
going between pipes and streams in either direction. However, I can see you
getting into problems coming *out* of TLS, because it is going to be very
hard to know whether TLS have over-read from the stream, and has
essentially stolen data into it's read buffer.

But by layering TLS on top of the pipe, you don't need to drop the pipe at
any time, and you can stay in pipelines mode most of the time, including
using any "kestrel" pieces like the "libuv" pipeline layer (instead of
managed sockets).

Any use?

**Comment by xqrzd** [comment]
Thanks for the tips, I was able to get it working by converting the SocketConnection to a stream, and passing that to SslStream (I still need a weird inner stream due to Kudu doing TLS handshake over protobuf). I ran into a minor problem; I still had a running task that was reading from the SocketConnection pipe, so I had to cancel that loop otherwise I got a 'read already in progress' exception. Finally, I converted the AsyncPipeStream back into a pipe.

The last piece now is being able to downgrade from TLS. In the above example, since that new TLS pipe has it's own read loop, I get the 'read already in progress' issue if I try to use the SocketConnection again. I'll have more time to experiment with this in a couple days, but thanks again for your help.

**Comment by mgravell** [comment]
Yeah, downgrading from TLS is a major pain, especially because it tends to
over-read, and with streams (unlike pipelines) there is no ability to say
"yeah, push this stuff back, I didn't want it after all".

**Comment by Drawaes** [comment]
I need to dig out some code. I did exactly this for an Ms SQL driver where I encrypt during the early auth and then drop.

**Comment by xqrzd** [comment]
As it turns out the problem exists between keyboard and chair, I have no need to downgrade from TLS as it isn't event supported. I should have read the [documentation](https://github.com/apache/kudu/blob/master/docs/design-docs/rpc.md#step-2-tls-handshake) closer. I got it working with pipelines, thanks again for your help!
