### ISSUE TITLE
ConnectionResetException missing Serializable attribute

### ISSUE THREAD

**Issue by oatsoda** [mgravell/Pipelines.Sockets.Unofficial#43]
https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/master/src/Pipelines.Sockets.Unofficial/ConnectionResetException.cs

> Type 'Pipelines.Sockets.Unofficial.ConnectionResetException' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute.  If the type is a collection, consider marking it with the CollectionDataContractAttribute.  See the Microsoft .NET Framework documentation for other supported types.

https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1032-implement-standard-exception-constructors?view=vs-2019

Seeing this when getting connection failures with the `StackExchange.Redis` assembly.

**Comment by mgravell** [comment]
implemented; I'm dubious as to what scenario would actually *require* them these days, but... they aren't onerous to add

**Comment by oatsoda** [comment]
I'll be honest, I can't quite remember the scenario myself at the moment. I'll see if I can re-trace my steps..!
