### ISSUE TITLE
How to find out when/if the reader/writer completed

### ISSUE THREAD

**Issue by sven-n** [mgravell/Pipelines.Sockets.Unofficial#47]
Hello,
Firstly, thank you for this nice library 👍 

My situation is, that I need a way to find out if a socket connection is closed or some kind of event which is fired when the reader or writer completed writing to the Pipe. Is there currently any way to get this information? If not, could it be added?
Thank you

**Comment by Drawaes** [comment]
When you try to read from the pipe there is a Is complete property on the result. For the writer I believe there is a similar property.

**Comment by sven-n** [comment]
Thanks, I already check this property in the consuming code. My issue is, that this code may not read to the end so the completion property doesn’t kick in. It would be nice to be able to determine the state of the connection from the outside.

**Comment by sven-n** [comment]
I found a way to get the current state of the connection. ```SocketConnection.ShutdownKind``` is unequal to ```None``  when the connection closed or any code called Complete on the reader or writer.

However, it would be great to have some kind of event, when this ShutdownKind is changed. Any chance that it will be added? I can send a PR, if you wish.

Thank you :)
