### ISSUE TITLE
Does this project only support .Net Core, instead of .Net Framework?

### ISSUE THREAD

**Issue by gaofeibupt** [mgravell/Pipelines.Sockets.Unofficial#51]
Hi, Marc

Firstly, thanks to your contributions of this project. When I used StackExchange.Redis, I found one problem. Here it is. One Property named "IsHardwareAccelerated" was not found under .Net Framework. It's in .Net Core. The problem code line https://github.com/mgravell/Pipelines.Sockets.Unofficial/blob/8cefce14b6e7c587fe72afe6435e9a07924f65b1/src/Pipelines.Sockets.Unofficial/Helpers.cs#L196
And with the document of "Vector.IsHardwareAccelerated Property" https://docs.microsoft.com/en-us/dotnet/api/system.numerics.vector.ishardwareaccelerated?view=netcore-3.1

I want to know, Does this project only support .Net Core, instead of .Net Framework? 😉

**Comment by mgravell** [comment]
The TFMs that it targets are clearly expressed in the nupkg, and includes
net461 and net472. It *should* resolve the correct versions automatically.
Are you seeing a problem, and if so: how are you referring the package? Do
you have a package-reference?

**Comment by gaofeibupt** [comment]
I used the "build.ps1" file and the compiler was .NetCore 3.1, the target framework was .NetFramework 4.7.2.

**Comment by mgravell** [comment]
And can you confirm that you saw a problem? If so, I'll try to repro. But:
the build should "just work".

**Comment by gaofeibupt** [comment]
Yeah, the build actually works well. The property named "Vector.IsHardwareAccelerated" is only implemented in dotnet core. How does it meet the requirements of dotnet framework? I'm not familiar with dotnet eco-system.

**Comment by mgravell** [comment]
System.Numerics.Vectors is available as an OOB package via NuGet; as long as you use the appropriate version: it is implemented. For example:

csproj:

```  xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />
  </ItemGroup>
</Project>
```

c#:

``` c#
using System;
using System.Numerics;

static class P
{
    static void Main()
    {
        Console.WriteLine(Vector.IsHardwareAccelerated);
    }
}
```

Which works *just fine* - in this case, on .NET 4.5

**Comment by gaofeibupt** [comment]
Thanks to your details guide. I tried this on my local computer, and did it successfully 🤣. The "System.Numerics"  is a OOB package, a standalone distribution. I need to import this OOB package manually. 
I have a stupid question, does this package released or developed by dotnet core community, instead of  the dotnet framework official? 😊

**Comment by mgravell** [comment]
By "this package", do you mean `System.Numerics.Vectors` or `Pipelines.Sockets.Unofficial`?

`System.Numerics.Vectors` is entirely official / Microsoft; the OOB here just means they have shipped updates via NuGet that apply retroactively to older frameworks; the "gotcha" here is that sometimes you get "assembly binding redirect" problems as a result - you can read all about that here (including what to do if you get a problem loading types): https://nickcraver.com/blog/2020/02/11/binding-redirects/

`Pipelines.Sockets.Unofficial` is - as the name suggests - completely unofficial and developed purely by myself.

**Comment by gaofeibupt** [comment]
Got it. Thank you very much
