### ISSUE TITLE
if the implementation of this library has relation ship  for Rio(Winsock registered I/O extensions) in Windows?

### ISSUE THREAD

**Issue by sgf** [mgravell/Pipelines.Sockets.Unofficial#52]
It seems that System.IO.Pipelines in .net core has some confusing concepts with RIO.It is said that System.IO.Pipelines does not apply to UDP protocol, but only to TCP protocol.
However, RIO is not related to the Socket protocol.  but RIO is only supported on windows 2012+.

http://www.serverframework.com/asynchronousevents/2012/08/winsock-registered-io-io-completion-port-performance.html

**Comment by mgravell** [comment]
No explicit relationship to RIO whatsoever. Somebody could probably use RIO as a driver for a pipe, but that isn't what this library does.

**Comment by sgf** [comment]
thanks
