### ISSUE TITLE
Question on StreamConnection.GetReader

### ISSUE THREAD

**Issue by rickj33** [mgravell/Pipelines.Sockets.Unofficial#6]
The call to StreamConnection.GetReader creates an AsyncStreamPipe. In the ctor of AsyncStreamPipe
if read is true, it ensures the stream is writable and if not throws an exception.
and if write is true it checks to ensure the stream is readable
because of this, when  trying to get a reader for a readonly file, an exception is thrown.

How can we get a reader for a readonly stream?

**Comment by mgravell** [comment]
That sounds a lot like I've inverted some boolean checks... in which case the fix is: I fix that

**Comment by mgravell** [comment]
should be fixed in 0.2.1-alpha.69, sorry
