### ISSUE TITLE
How to get a Multisegment stream backed ReadOnlySequence

### ISSUE THREAD

**Issue by Wraith2** [mgravell/Pipelines.Sockets.Unofficial#7]
I'm writing something to parse a utf8 based network protocol and I'm trying to setup multiple segments so I can ensure the parser handles the boundaries correctly without having to take the data off the wire each time. It may well be the case that I've misunderstood the pipelines api but I can't figure out how to get a multi segment sequence setup using a stream. 

The code I'm using so far is this:
```
public static async Task TestParser()
{
	byte[] msg = new byte[] { 239, 187, 191, 76, 111, 103, 111, 110, 58, 58, 68, 73, 68, 35, 95, 123, 101, 97, 101, 102, 50, 50, 57, 102, 45, 52, 51, 56, 97, 45, 52, 52, 52, 52, 45, 97, 102, 55, 56, 45, 98, 56, 51, 101, 101, 49, 100, 52, 97, 56, 49, 101, 125, 126, 65, 112, 112, 78, 97, 109, 101, 35, 80, 68, 65, 126, 65, 112, 112, 86, 101, 114, 115, 105, 111, 110, 35, 49, 46, 51, 51, 126, 69, 110, 97, 98, 108, 101, 67, 111, 109, 112, 114, 101, 115, 115, 105, 111, 110, 35, 84, 114, 117, 101, 64, 64 };

	using (var memory = new MemoryStream())
	{
		int length = 5;
		var duplex = StreamConnection.GetDuplex(memory);
		for (int count = 0; count<msg.Length/length; count++)
		{
			duplex.Output.Write(msg.AsSpan(count*length, length));
		}
		if (msg.Length%length>0)
		{
			duplex.Output.Write(msg.AsSpan(msg.Length-(msg.Length%length)));
		}
		await duplex.Output.FlushAsync();

		duplex.Output.Complete();

		var reader = await duplex.Input.ReadAsync();

		ReadOnlySequence<byte> buffer = reader.Buffer; // always a zero length single segment, what am i getting wrong?
	}
}
```

**Comment by mgravell** [comment]
It sounds like what you actually want here is just a single Pipe. A
duplex-pipe over a MemoryStream is a bad idea, as it won't rewind the
stream. A single pipe naps to MemoryStream automatically: just use a single
Pipe, via new Pipe, and access the reader/writer from there. No
MemoryStream required.

**Comment by Wraith2** [comment]
That gets me the data but as a single segment and what I'm looking for is a way to test the segment handover so I really want to try and get multiple segments. Presumably whatever I do with MemoryStream as backing is going to end up with the single buffer from the stream exposed as a single segment so I need another way.

**Comment by mgravell** [comment]
If you want multiple segments, you're going to have to play with the
PipeOptions when creating the pipe, and/or *write more data* (meaning: go
over the segment boundary)

**Comment by Wraith2** [comment]
Yup, got that just after I posted my earlier reply. I edited to reflect that but the email won't have had that in. Looks like it's working and I can bias by odd bytes interleaving utf preambles of 3 bytes if I need to. Thanks for the help.

**Comment by Drawaes** [comment]
For testing multi segment handling I wrote my own segment implementation and. Factory that takes in multiple arrays and returns  Readonlysequence. That way your unit test focuses on parsing not pipes

**Comment by Wraith2** [comment]
That sounds like a useful bit of code to have. Any chance of getting that integrated into this library as a tool?

**Comment by Drawaes** [comment]
If @mgravell is interested in it I can take a look at making it public sure.

**Comment by mgravell** [comment]
Yes, I think that would be a useful addition. Your code, though; your
choice!

**Comment by mgravell** [comment]
re the original `MemoryStream` usage; from 0.2.1-alpha.79 the lib detects this and issues guidance
